void limparMatriz();
void imprimirMatriz();
int ponteiroNulo(Posicao *p);
void salvarJogo();
int carregarJogo();
void config();
void gerarDoce();
void colocaObjeto();
void jogar();
void movimentar(Posicao p);
void sair();
void limparTela();
